### ISSUE TITLE
og:site_name does not fallback to site title

### ISSUE THREAD

**Issue by Maybach91** [diesdasdigital/kirby-meta-knight#36]
According to the Inputfields Help’ it says the `og:site_name` [open_graph.yml:82](https://github.com/diesdasdigital/kirby-meta-knight/blob/829835f1feb113d8890ed1b14f4f6ba171ebe291/blueprints/fields/open_graph.yml#L23) property will fallback to the site name.
```yml
og_site_name:
    label: OG Site Name
    help: If your object is part of a larger web site, the name which should be displayed for the overall site. Will use *site title* as fallback.
    type: text
    width: 1/2
```
But in the `meta_information.php`[Line 82](https://github.com/diesdasdigital/kirby-meta-knight/blob/829835f1feb113d8890ed1b14f4f6ba171ebe291/snippets/meta_information.php#L82) i cannot see, that it will fallback to the title:
```php
<meta property="og:site_name" content="<?= $page->og_site_name()->or($site->og_site_name()) ?>">
```

Is that intended?
