### ISSUE TITLE
Change text limit to maxlength where needed

### ISSUE THREAD

**Issue by ktryndchrs** [diesdasdigital/kirby-meta-knight#45]
Hello there,

First of all, thank you for the amazing work and maintenance on this great plugin! 

Kirby no longer use `limit` to set a character limit their input fields (text, textarea, etc.), but `maxlength`.
I suggest you to update it here: `kirby-meta-knight/blueprints/fields/twitter.yml`

Also, I think the char limit is not the right one.

```
type: group
fields:
  (...)
  twitter_title:
    label: Twitter Title
    type: text
    👉 limit: 70
    help: The title of your page as it should appear on Twitter. Will use *page title* as fallback.
  twitter_description:
    label: Twitter Description
    type: text
    👉 limit: 300
    help: A one to two sentence description of your page. Will use *page description* and *site description* as fallbacks.
  (...)
```
